### ISSUE TITLE
on windows11

### ISSUE THREAD

**Issue by rifu-a** [Shougo/dpp.vim#16] opened 2024-01-29 19:11 UTC
Is dpp not compatible with windows?

The function cannot be used even if you use the following

https://github.com/Shougo/shougo-s-github

https://github.com/neovim/neovim/releases
NVIM v0.10.0-dev-2236+g5e5b004da
Build type: RelWithDebInfo
LuaJIT 2.1.1706185428

https://github.com/denoland/deno/releases/tag/v1.40.2

XDG_CONFIG_HOME
  C:\Users\rifu\.config
XDG_CACHE_HOME
  C:\Users\rifu\.cache
XDG_DATA_HOME
  C:\Users\rifu\.local\share
XDG_STATE_HOME
  C:\Users\rifu\.local\state
HOME
  C:\Users\rifu
DENO_DIR
   C:\Users\rifu\.cache\deno

:message
dpp load_state() is failed
:call dpp#async_ext_action('installer', 'install')
:message
dpp.vim is not initialized yet.
Please check dpp#min#load_state() is suceeded.

**Comment by Shougo** [comment] 2024-01-30 00:07
Please check the messages.
dpp.vim is not initialized.  I think denops.vim is not loaded properly.

**Comment by Shougo** [comment] 2024-01-30 00:08
I have tested the vimrc and it works on Windows 10 environment.  But it is for my environment.
I don't guarantee my environment works on other environment.

**Comment by Shougo** [comment] 2024-01-30 00:19
Note:  Denops.vim loading takes time especially if you use Windows and it is first install.

**Comment by rifu-a** [comment] 2024-01-30 01:01
Thank you for your reply.

I understand that the initial loading of the Denops is slow.

I have confirmed that there is no problem with loading the Denops using the sample below.
https://github.com/vim-denops/denops-helloworld.vim

The same phenomenon occurs even when starting neovim for the second time.

The settings described in dpp help are also similar.
EXAMPLES                                                        *dpp-examples*
>
	" Ward off unexpected things that your distro might have made, as
	" well as sanely reset options when re-sourcing .vimrc
	set nocompatible
	
	" Set dpp base path (required)
	const s:dpp_base = '~/.cache/dpp/'
	
	" Set dpp source path (required)
	const s:dpp_src = '~/.cache/dpp/repos/github.com/Shougo/dpp.vim'
	const s:denops_src = '~/.cache/dpp/repos/github.com/denops/denops.vim'
	
	" Set dpp runtime path (required)
	execute 'set runtimepath^=' .. s:dpp_src
	
	if s:dpp_base->dpp#min#load_state()
	  " NOTE: dpp#make_state() requires denops.vim
	  execute 'set runtimepath^=' .. s:denops_src
	  autocmd User DenopsReady
	  \ call dpp#make_state(s:dpp_base, '{TypeScript config file path}')
	endif
	
	" Attempt to determine the type of a file based on its name and
	" possibly its " contents. Use this to allow intelligent
	" auto-indenting " for each filetype, and for plugins that are
	" filetype specific.
	filetype indent plugin on
	
	" Enable syntax highlighting
	if has('syntax')
	  syntax on
	endif
<
Q: |DenopsReady| is not executed when |dpp#min#load_state()| is failed.

A: "plugin/denops.vim" is not loaded.  I think you have enabled "--noplugin".
You need to execute "plugin/denops.vim" manually by |:runtime| command.

>
  runtime! plugin/denops.vim
<

I've been using it since Unite, so I'd definitely like to use it.

**Comment by Shougo** [comment] 2024-01-30 01:09
You need to upload the minimal init.vim and describe what you are executed specifically.

I think `call dpp#make_state()` is not done. It is asynchronous.

**Comment by rifu-a** [comment] 2024-01-31 01:30
Even if I run it with the smallest file, the problem remains the same.

[a.zip](https://github.com/Shougo/dpp.vim/files/14106014/a.zip)
:message
[denops] Spawn server [1/4]
[denops] Server started: ['deno', 'run', '-q', '--no-lock', '-A', 'C:\Users\rifu\.cache\dpp\repos\github.com\vim-denops\denops.vim\denops\@denops-private\cli.ts', '--quiet', '--identity', '--port', '0']                                      
[denops] Server listen: 127.0.0.1:54362                                                                                 
[denops] Connecting to channel `127.0.0.1:54362` [1/4]                                                                  
[denops] Channel connected (127.0.0.1:54362)                                                                            
[denops] DenopsReady                                                                                                    
[denops] 0 plugins are discovered

**Comment by Shougo** [comment] 2024-01-31 02:32
> [denops] DenopsReady

`DenopsReady` is fired.  But `dpp#make_state()` is fired and exited?  Please check it.

```vim
autocmd User Dpp:makeStatePost
      \ : echohl WarningMsg
      \ | echomsg 'dpp make_state() is done'
      \ | echohl NONE
```

I use this.

**Comment by rifu-a** [comment] 2024-01-31 02:50
I will attach the confirmation results.
I think dpp#make_sate() is activated.
If you enter the wrong path for dpp.ts, a loading error will occur.
It is not possible to determine whether there is a problem in dpp.ts or not.

[init.vim.txt](https://github.com/Shougo/dpp.vim/files/14106566/init.vim.txt)
:message
1
2
3
[denops] Spawn server [1/4]                                                                                             
[denops] Server started: ['deno', 'run', '-q', '--no-lock', '-A', 'C:\Users\rifu\.cache\dpp\repos\github.com\vim-denops\denops.vim\denops\@denops-private\cli.ts', '--quiet', '--identity', '--port', '0']                                      
[denops] Server listen: 127.0.0.1:54888                                                                                 
[denops] Connecting to channel `127.0.0.1:54888` [1/4]                                                                  
[denops] Channel connected (127.0.0.1:54888)                                                                            
[denops] DenopsReady                                                                                                    
[denops] 0 plugins are discovered

**Comment by Shougo** [comment] 2024-01-31 03:23
`dpp make_state() is done` is not found.
Please wait the execution.

**Comment by rifu-a** [comment] 2024-01-31 03:41
What does it mean?
>Please wait the execution.

I wait 30 minutes after starting neovim, but nothing changes.
I've been using this for about 3 weeks and have never seen dpp make_state() run.
My home PC and work PC are in the same situation.

**Comment by Shougo** [comment] 2024-01-31 04:19
Really?  Please test it on non Windows environment.

I will test your code.
You need to upload `dpp.ts` file.

I will close it if I cannot reproduce the problem with the minimal files.

**Comment by Shougo** [comment] 2024-01-31 04:22
vimrc

```vim
set nocompatible

const s:dpp_base = '~/work/test/dpp/'->expand()
let $BASE_DIR = '<sfile>'->expand()->fnamemodify(':h')
let g:denops#debug = v:true

const s:dpp_src = '~/work/dpp.vim'->expand()
const s:denops_src = '~/work/denops.vim'->expand()

const s:dpp_ext_1_src = '~/work/dpp-ext-lazy'->expand()
const s:dpp_ext_2_src = '~/work/dpp-ext-installer'->expand()
const s:dpp_ext_3_src = '~/work/dpp-ext-local'->expand()
const s:dpp_ext_4_src = '~/work/dpp-ext-packspec'->expand()
const s:dpp_ext_5_src = '~/work/dpp-ext-toml'->expand()
const s:dpp_ext_6_src = '~/work/dpp-protocol-gity'->expand()

execute 'set runtimepath^=' .. s:dpp_src
execute 'set runtimepath^=' .. s:dpp_ext_1_src

echomsg '1'
autocmd User Dpp:makeStatePost
      \ : echohl WarningMsg
      \ | echomsg 'dpp make_state() is done'
      \ | echohl NONE
echomsg '2'

if s:dpp_base->dpp#min#load_state()
  execute 'set runtimepath^=' .. s:dpp_ext_2_src
  execute 'set runtimepath^=' .. s:dpp_ext_3_src
  execute 'set runtimepath^=' .. s:dpp_ext_4_src
  execute 'set runtimepath^=' .. s:dpp_ext_5_src
  execute 'set runtimepath^=' .. s:dpp_ext_6_src

  execute 'set runtimepath^=' .. s:denops_src
  autocmd User DenopsReady
  \ call dpp#make_state(s:dpp_base, '$BASE_DIR/dpp.ts'->expand())
  echomsg '3'
endif


filetype indent plugin on

if has('syntax')
  syntax on
endif
```

**Comment by Shougo** [comment] 2024-01-31 04:25
> I wait 30 minutes after starting neovim, but nothing changes.

`dpp make_state() is done` is not found?  30 minutes?  Really?

> It is not possible to determine whether there is a problem in dpp.ts or not.

It seems your `dpp.ts` problem.   You need to upload it.

**Comment by rifu-a** [comment] 2024-01-31 08:32
>dpp make_state() is done is not found? 30 minutes? Really?

It's true because there's nothing going on about the lie either.

>It seems your dpp.ts problem. You need to upload it.

The dpp.ts file is included within a.zip.

>Really? Please test it on non Windows environment.

It is possible to boot ubuntu in a virtual environment.
Is confirmation really necessary for that work?

>vimrc

Windows path length settings have been changed.
I don't think changing to the work directory has any effect.
I'll try it anyway.

**Comment by Shougo** [comment] 2024-01-31 09:34
OK.  Reproduced.  It is bug.

Please update dpp.vim.

**Closed as completed by Shougo** 2024-01-31 09:34 UTC
Labels: bug

**Comment by Shougo** [comment] 2024-01-31 09:52
`dpp#make_state()` is called, but dpp.vim is not registered(skipped).
So your script does not work.

**Comment by rifu-a** [comment] 2024-02-01 02:57
Bug fix. Excellent!
There were no problems in this environment either.

ご対応頂き感謝です！！やっとdduddcに入っていけます！
これからも楽しいツールの提供お待ちしております！
(英語だとニュアンスが作れないので日本語で失礼します)
